[workspace]
resolver = "2"
members = ["core", "parser"]

[workspace.package]
authors = ["Jerome David <programingjd@gmail.com>"]
license = "MIT"
repository = "https://github.com/programingjd/min_http11"
